import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { RegisterLink, LoginLink, LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  console.log(user);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen">
          <div className="bg-gray-300 p-3">
            <header className="container mx-auto  flex justify-between gap-3">
              <h2 className="text-3xl sm:block hidden">Logo</h2>
              <nav className="flex gap-2">
                <Link href="/">Home</Link>
                <Link href="/dashboard">Profile</Link>
              </nav>
              <div>
                {user ? (
                  <>

                    <LogoutLink className="text-red-500">Log out</LogoutLink>
                  </>
                ) : (
                  <>
                    <LoginLink className="text-blue-600 font-semibold mr-2">Log in</LoginLink>
                    <RegisterLink className="text-red-500 font-semibold">Sign up</RegisterLink>
                  </>
                )}
              </div>
            </header>
          </div>
          {children}
          <footer className="bg-gray-300">
            <div className="container mx-auto text-center py-20 text-black font-bold text-4xl">
              Footer
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
